name: Continues deployment

on:
  workflow_dispatch:

  push:
    branches:
      - main

    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: docker build and push to ghcr
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}
          registry: ghcr.io
          image_name: ${{ secrets.MS_NAME }}
          image_tag: latest

  docker-arm:
      runs-on: ubuntu-latest
      env:
        RUNNER_ARCH: arm64
      timeout-minutes: 5
      permissions:
        packages: write
        contents: read

      steps:
        - uses: actions/checkout@v2

        - name: docker build and push to ghcr
          uses: whoan/docker-build-with-cache-action@v5
          with:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GH_ACCESS_TOKEN }}
            registry: ghcr.io
            image_name: ${{ secrets.MS_NAME }}
            image_tag: latest
